### ISSUE TITLE
Section title echoed directly without formatting

### ISSUE THREAD

**Issue by mudrd8mz** [Edunao/moodle-format_ludic#1]
Section titles are not supposed to be echoed directly, but always processed through `format_string()`. Violating it not only prevents from some functionality (such as filters support) but may also represent a potentially security issue.

### Steps to reproduce ###

1. Set up a course using Ludic format
2. Define a section title as `<script>alert(/xss/);</script>Lesson 1`
3. Visit the course page

Expected behaviour: JS is cleaned up and not executed.

What actually happens:

![image](https://user-images.githubusercontent.com/85831/98955021-b8768400-24fe-11eb-86df-d0bacd9d5925.png)

**Comment by mudrd8mz** [comment]
https://docs.moodle.org/dev/Security:Cross-site_scripting

**Comment by Celine-Edunao** [comment]
Hi mudrd8mz, 

Thank you very much for your feedback !
We fixed this problem in version 3.5.4
