### ISSUE TITLE
Deprecated code - array_key_exists() on objects

### ISSUE THREAD

**Issue by DKSteffensen** [Edunao/moodle-format_ludic#4]
Hello,

After installation on a moodle 3.9 site, (with php 7.4) - we encountered this problem:
![image](https://user-images.githubusercontent.com/9873412/117443239-2c3a9c00-af38-11eb-8675-4272666b8060.png)

Kind regards,
Daniel Kristian Steffensen

**Comment by franzhansi** [comment]
Hello Edunao,

Anything new to this?

- Kenneth

**Comment by Celine-Edunao** [comment]
Hello, 

This should be fixed with today's commit (version 3.5.6)

Thanks for your feedback !
